"""add conversations and messages tables for shared inbox

Revision ID: 7e40fcbc6b93
Revises: 8b924529b91b
Create Date: 2026-04-30 12:36:02.096672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e40fcbc6b93'
down_revision: Union[str, None] = '8b924529b91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number_id', sa.BigInteger(), nullable=False),
    sa.Column('jid', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.Text(), nullable=True),
    sa.Column('unread_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['whatsapp_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number_id', 'jid', name='uq_conversations_number_jid')
    )
    op.create_index(op.f('ix_conversations_kind'), 'conversations', ['kind'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_number_id'), 'conversations', ['number_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('sender_jid', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='received', nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'wa_message_id', name='uq_messages_conv_wa_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_number_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_kind'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
