"""add whatsapp_numbers table

Revision ID: ea3787350acc
Revises: 886c2df6db35
Create Date: 2026-04-30 06:00:02.280876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea3787350acc'
down_revision: Union[str, None] = '886c2df6db35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_numbers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('msisdn', sa.String(length=32), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_whatsapp_numbers_msisdn'), 'whatsapp_numbers', ['msisdn'], unique=False)
    op.create_index(op.f('ix_whatsapp_numbers_status'), 'whatsapp_numbers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_numbers_status'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_msisdn'), table_name='whatsapp_numbers')
    op.drop_table('whatsapp_numbers')
    # ### end Alembic commands ###
