"""add serper budget columns to campaigns

Revision ID: 038343ccfab2
Revises: 79c298b304d9
Create Date: 2026-04-27 12:47:34.807065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038343ccfab2'
down_revision: Union[str, None] = '79c298b304d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('max_credits_serper', sa.Integer(), server_default='500', nullable=False))
    op.add_column('campaigns', sa.Column('serper_credits_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'serper_credits_used')
    op.drop_column('campaigns', 'max_credits_serper')
    # ### end Alembic commands ###
