"""add whatsapp enrichment columns to leads

Revision ID: 886c2df6db35
Revises: 3154085e26c7
Create Date: 2026-04-29 13:50:41.141172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '886c2df6db35'
down_revision: Union[str, None] = '3154085e26c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('verified_group_name', sa.String(length=200), nullable=True))
    op.add_column('leads', sa.Column('verified_group_description', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('last_validated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'last_validated_at')
    op.drop_column('leads', 'verified_group_description')
    op.drop_column('leads', 'verified_group_name')
    # ### end Alembic commands ###
