"""initial schema

Revision ID: 79c298b304d9
Revises: 
Create Date: 2026-04-27 12:31:48.884665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79c298b304d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industries', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('locations', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('negative_locations', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('platforms', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('url_cache',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invite_id', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('detected_geo', sa.String(length=8), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('geo_fit', sa.Integer(), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_scored_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_id')
    )
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_total_score'), 'leads', ['total_score'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('source_platform', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_campaign_id'), 'queries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_queries_status'), 'queries', ['status'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_query_id'), 'search_results', ['query_id'], unique=False)
    op.create_index(op.f('ix_search_results_status'), 'search_results', ['status'], unique=False)
    op.create_index('ix_search_results_url', 'search_results', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_results_url', table_name='search_results')
    op.drop_index(op.f('ix_search_results_status'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_query_id'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_queries_status'), table_name='queries')
    op.drop_index(op.f('ix_queries_campaign_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_leads_total_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('url_cache')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
