"""add status column to leads

Revision ID: 6a4da1412fab
Revises: a9bb663053cf
Create Date: 2026-04-29 06:46:42.342860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4da1412fab'
down_revision: Union[str, None] = 'a9bb663053cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('status', sa.String(length=16), server_default='pending', nullable=False))
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_column('leads', 'status')
    # ### end Alembic commands ###
