"""add broadcast_jobs and outbound_messages tables

Revision ID: 8b924529b91b
Revises: ea3787350acc
Create Date: 2026-04-30 09:45:45.810049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b924529b91b'
down_revision: Union[str, None] = 'ea3787350acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('total_targets', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('min_delay_seconds', sa.Integer(), server_default='3', nullable=False),
    sa.Column('max_delay_seconds', sa.Integer(), server_default='15', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['number_id'], ['whatsapp_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_jobs_number_id'), 'broadcast_jobs', ['number_id'], unique=False)
    op.create_index(op.f('ix_broadcast_jobs_status'), 'broadcast_jobs', ['status'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('jid', sa.String(length=80), nullable=False),
    sa.Column('group_subject', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['broadcast_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_messages_job_id'), 'outbound_messages', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_messages_job_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_broadcast_jobs_status'), table_name='broadcast_jobs')
    op.drop_index(op.f('ix_broadcast_jobs_number_id'), table_name='broadcast_jobs')
    op.drop_table('broadcast_jobs')
    # ### end Alembic commands ###
