"""add current_stage to campaigns

Revision ID: 1a2515ccb857
Revises: 83b0e2a8ac10
Create Date: 2026-04-27 16:13:11.565882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2515ccb857'
down_revision: Union[str, None] = '83b0e2a8ac10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('current_stage', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'current_stage')
    # ### end Alembic commands ###
