"""lead uniqueness: drop UNIQUE(invite_id), add UNIQUE(campaign_id, invite_id)

Revision ID: a9bb663053cf
Revises: 1a2515ccb857
Create Date: 2026-04-28 11:19:46.351728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bb663053cf'
down_revision: Union[str, None] = '1a2515ccb857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('leads_invite_id_key'), 'leads', type_='unique')
    op.create_index(op.f('ix_leads_invite_id'), 'leads', ['invite_id'], unique=False)
    op.create_unique_constraint('uq_leads_campaign_invite', 'leads', ['campaign_id', 'invite_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_leads_campaign_invite', 'leads', type_='unique')
    op.drop_index(op.f('ix_leads_invite_id'), table_name='leads')
    op.create_unique_constraint(op.f('leads_invite_id_key'), 'leads', ['invite_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
