"""add firecrawl budget columns

Revision ID: 871a4c887dfc
Revises: 0acad4eb3f26
Create Date: 2026-04-27 13:04:36.886026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871a4c887dfc'
down_revision: Union[str, None] = '0acad4eb3f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('max_credits_firecrawl', sa.Integer(), server_default='200', nullable=False))
    op.add_column('campaigns', sa.Column('firecrawl_credits_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'firecrawl_credits_used')
    op.drop_column('campaigns', 'max_credits_firecrawl')
    # ### end Alembic commands ###
