"""add sender_name to messages

Revision ID: e4459abc73e9
Revises: 7e40fcbc6b93
Create Date: 2026-04-30 12:51:09.849856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4459abc73e9'
down_revision: Union[str, None] = '7e40fcbc6b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sender_name')
    # ### end Alembic commands ###
